language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql

script: bundle exec rspec spec

# Set up database
before_script:
  - psql -c 'create database New_World_Radio_test;' -U postgres
  - bundle exec rake db:schema:load
# You may need this for rails 3.2 applications
  - bundle exec rake db:test:prepare
